language: python
python:
  - 3.8
install:
  - pip install pytest
scripts:
  - pylint *.py
  - pytest

notifications:
  email:
    recipients:
      - amol@earthsense.co
    on_success: always
    on_failure: always